# Exercices NumPy 

<span style="color:red">Réalisation de tous les exercices sans utiliser de boucles.</span>
---

In [3]:
import numpy as np
import pandas as pd
# Configuration de la précision d'affichage
np.set_printoptions(precision=2, suppress=True)
print("NumPy version:", np.__version__)

NumPy version: 2.5.3


## Exercice 1 : Création et restructuration d'un tableau (1D → 2D)

**Objectif :**
1. Créez un vecteur 1D contenant les entiers de 1 à 20.
2. Transformez-le en une matrice 2D de dimensions $4 \times 5$.

In [ ]:
# VOTRE CODE ICI
data_1d = np.arange(1, 21)
data_2d = pd.DataFrame(data_1d.reshape(4, 5))

print(data_1d)

print("-"*50)

print(data_2d)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
--------------------------------------------------
    0   1   2   3   4
0   1   2   3   4   5
1   6   7   8   9  10
2  11  12  13  14  15
3  16  17  18  19  20


In [36]:
a = [
    [11,12,13], 
    [21,22, 23], 
    [31, 32, 33]
]
a
A = np.array(a)
A
A.ndim
A.shape
A.size
A[1, 2]
A[0:3,2]
X = np.array(
    [
        [1, 0], 
        [0, 1]
    ])
X
Y = np.array(
    [
        [2, 1], 
        [1, 2]
    ])
Y

Z = X + Y
Z
ZZ = 2 * Z

ZZ


array([[6, 2],
       [2, 6]])

## Exercice 2 : Extraction par masque booléen (1D)

**Objectif :**
Soit un vecteur 1D de 15 nombres aléatoires entre 0 et 50. Extrayez tous les éléments strictement supérieurs à 25 **ET** pairs.

In [56]:

# VOTRE CODE ICI
np.random.seed(44)
data_1d = np.random.randint(0, 51, size=15)
# print(data_1d)
extracted_elements = data_1d[((data_1d > 25) & (data_1d % 2 == 0))]

print(extracted_elements)

[32 42]


## Exercice 3 : Inversion et inversion par colonnes (1D et 2D)

**Objectif :**
1. Inversez l'ordre des éléments d'un vecteur 1D de taille 10.
2. Soit une matrice $4 \times 4$, inversez l'ordre de ses colonnes (la dernière colonne devient la première).

In [75]:
# VOTRE CODE ICI
data_1D = np.random.randint(0,111,size=10)

print(f"befor : {data_1D}")
print(f"befor : {data_1D[::-1]}")

data_2D = [
    [1,2,3,100],
    [4,5,6,200],
    [7,8,9,300],
    [7,8,9,400]
]
data_2D = pd.DataFrame(data_2D)
print(f"after : \n{data_2D}")
x = data_2D.iloc[:,::-1]
print("befor : \n")
print(x)


befor : [82 15 17 68 64 56 50 17 63 76]
befor : [76 63 17 50 56 64 68 17 15 82]
after : 
   0  1  2    3
0  1  2  3  100
1  4  5  6  200
2  7  8  9  300
3  7  8  9  400
befor : 

     3  2  1  0
0  100  3  2  1
1  200  6  5  4
2  300  9  8  7
3  400  9  8  7


## Exercice 4 : Statistique par axe (2D)

**Objectif :**
Soit une matrice $5 \times 3$ d'entiers aléatoires entre 1 et 100.
1. Calculez la moyenne globale de la matrice.
2. Calculez la somme des éléments pour chaque **colonne**.
3. Obtenez la valeur maximale pour chaque **ligne**.

In [76]:
# VOTRE CODE ICI
matrice = np.random.randint(1, 101, size=(5, 3))

print(matrice)
print("-" * 30)

moyenne_globale = np.mean(matrice)
print(f"moyenne_globale: {moyenne_globale}")

somme_colonnes = np.sum(matrice, axis=0)
print(f"somme_colonnes: {somme_colonnes}")

max_lignes = np.max(matrice, axis=1)
print(f"max_lignes : {max_lignes}")


[[25 27 60]
 [23 14 61]
 [93 80 60]
 [60 33 30]
 [20 26 71]]
------------------------------
moyenne_globale: 45.53333333333333
somme_colonnes: [221 180 282]
max_lignes : [60 61 93 60 71]


## Exercice 5 : Remplacement des valeurs manquantes (1D / 2D)

**Objectif :**
Soit le tableau : `arr = np.array([1.0, 2.0, np.nan, 4.0, np.nan, 6.0])`.
Remplacez toutes les valeurs `NaN` par la moyenne des valeurs non manquantes du tableau.

In [ ]:
# VOTRE CODE ICI
arr = np.array([1.0, 2.0, np.nan, 4.0, np.nan, 6.0])
m = np.nanmean(arr)
c = np.nan_to_num(arr, nan = m)
print(c)

[1.   2.   3.25 4.   3.25 6.  ]


## Exercice 6 : Concaténation et empilement (2D)

**Objectif :**
Soit deux matrices $A$ et $B$ de dimensions $3 \times 2$.
1. Empilez-les verticalement pour obtenir une matrice $6 \times 2$.
2. Empilez-les horizontalement pour obtenir une matrice $3 \times 4$.

In [84]:
# VOTRE CODE ICI
A = np.array([
    [1, 2],
    [3, 4],
    [5, 6]]
)

B = np.array(
    [[7, 8],
    [9, 10],
    [11, 12]]
)
vertical = np.vstack((A,B))
horizontal = np.hstack((A,B))

print(vertical)
print("t"*22)
print(horizontal)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
tttttttttttttttttttttt
[[ 1  2  7  8]
 [ 3  4  9 10]
 [ 5  6 11 12]]


## Exercice 7 : Recherche d'indices spécifiques (`np.where`) (1D)

**Objectif :**
Soit un vecteur 1D de 12 valeurs réelles. Récupérez les **indices** (et non les valeurs) de tous les éléments compris entre 10 et 20 inclus.

In [89]:
# VOTRE CODE ICI
d = np.random.randint(1,30,size=12)
print(d)

s = np.where((d >= 10) & (d <= 20))
print(s)
print(d[s])



[ 7 26 14 19 26  6 25 16 11 26 13 23]
(array([ 2,  3,  7,  8, 10]),)
[14 19 16 11 13]


## Exercice 8 : Calcul de la diagonale et trace (2D)

**Objectif :**
Générez une matrice carrée $4 \times 4$ d'entiers.
1. Extrayez les éléments de la diagonale principale sous forme de vecteur 1D.
2. Calculez la somme de ces éléments (la trace) en utilisant la fonction NumPy dédiée.

In [ ]:
# VOTRE CODE ICI


## Exercice 9 : Masquage conditionnel & Remplacement rapide (1D)

**Objectif :**
Créez un vecteur 1D de 20 entiers aléatoires entre -10 et 10. Sans utiliser de boucle for ni d'instructions if, remplacez tous les nombres négatifs impairs par leur carré, et tous les nombres positifs pairs par 0.

In [ ]:
# VOTRE CODE ICI


## Exercice 10 : Extraction par glissement / Fenêtres glissantes (1D)

**Objectif :**
Soit un vecteur 1D $V = [1, 2, 3, 4, 5, 6, 7, 8]$. Générez une matrice 2D représentant toutes les sous-fenêtres glissantes de taille 3 avec un pas (stride) de 1.Résultat attendu :$$\begin{bmatrix} 1 & 2 & 3 \\ 2 & 3 & 4 \\ 3 & 4 & 5 \\ \dots & \dots & \dots \end{bmatrix}$$

In [ ]:
# VOTRE CODE ICI


## Exercice 11 : Extraction des k plus grands éléments par ligne (2D)

**Objectif :**
Soit une matrice 2D de dimensions $6 \times 8$ remplie d'entiers aléatoires. Extrayez, pour chaque ligne, les 3 plus grandes valeurs et leurs indices respectifs, triés par ordre décroissant.

In [ ]:
# VOTRE CODE ICI